In [58]:
import yfinance as yf
import pandas as pd
import time

In [94]:
stocks = [
    "AGHOL.IS",
    "AGROT.IS",
    "AKFGY.IS",
    "AKFYE.IS",
    "AKSA.IS",
    "AKSEN.IS",
    "ALARK.IS",
    "ALFAS.IS",
    "AEFES.IS",
    "ARCLK.IS",
    "ARDYZ.IS",
    "ASELS.IS",
    "ASTOR.IS",
    "BTCIM.IS",
    "BERA.IS",
    "BIMAS.IS",
    "BRSAN.IS",
    "BRYAT.IS",
    "BFREN.IS",
    "CCOLA.IS",
    "CWENE.IS",
    "CANTE.IS",
    "CIMSA.IS",
    "DOHOL.IS",
    "DOAS.IS",
    "ECZYT.IS",
    "EGEEN.IS",
    "ECILC.IS",
    "EKGYO.IS",
    "ENJSA.IS",
    "ENERY.IS",
    "ENKAI.IS",
    "EREGL.IS",
    "EUREN.IS",
    "EUPWR.IS",
    "FROTO.IS",
    "GESAN.IS",
    "GOLTS.IS",
    "GUBRF.IS",
    "SAHOL.IS",
    "HEKTS.IS",
    "ISGYO.IS",
    "ISMEN.IS",
    "IZENR.IS",
    "KLSER.IS",
    "KRDMD.IS",
    "KTLEV.IS",
    "KAYSE.IS",
    "KCAER.IS",
    "KCHOL.IS",
    "KONTR.IS",
    "KONYA.IS",
    "KOZAL.IS",
    "KOZAA.IS",
    "LMKDC.IS",
    "MAVI.IS",
    "MIATK.IS",
    "MGROS.IS",
    "OBAMS.IS",
    "ODAS.IS",
    "OTKAR.IS",
    "OYAKC.IS",
    "PGSUS.IS",
    "PEKGY.IS",
    "PETKM.IS",
    "QUAGR.IS",
    "REEDR.IS",
    "SASA.IS",
    "SDTTR.IS",
    "SMRTG.IS",
    "SOKM.IS",
    "TABGD.IS",
    "TAVHL.IS",
    "TKFEN.IS",
    "TKNSA.IS",
    "TOASO.IS",
    "TUKAS.IS",
    "TCELL.IS",
    "TMSN.IS",
    "TUPRS.IS",
    "THYAO.IS",
    "TTKOM.IS",
    "TTRAK.IS",
    "TURSG.IS",
    "SISE.IS",
    "ULKER.IS",
    "VESBE.IS",
    "VESTL.IS",
    "YYLGD.IS",
    "YEOTK.IS",
    "ZOREN.IS",
    "BINHO.IS",
]

In [95]:
data_array = []

for stock in stocks:
    # download fundamental data
    data = yf.Ticker(stock)
    fundamentals = data.info
    financials = data.get_financials()
    balance_sheet = data.get_balance_sheet()
    income = data.get_income_stmt()
    try:
        data_array.append(
            {
                "stock": stock,
                "ebit": financials.loc["EBIT"].iloc[0],
                "enterpriseValue": fundamentals["enterpriseValue"],
                "netPPE": balance_sheet.loc["NetPPE"].iloc[0],
                "workingCapital": balance_sheet.loc["WorkingCapital"].iloc[0],
            }
        )
    except Exception as e:
        print(f"Error for {stock}: {e}")
        continue

    time.sleep(1)

Error for BRYAT.IS: 'NetPPE'
Error for CWENE.IS: 'EBIT'
Error for ENERY.IS: 'EBIT'
Error for SAHOL.IS: 'EBIT'
Error for KTLEV.IS: 'EBIT'
Error for TURSG.IS: 'WorkingCapital'

In [96]:
df = pd.DataFrame(data_array)
df

       stock          ebit  enterpriseValue        netPPE  workingCapital
0   AGHOL.IS  7.657792e+10     248437800960  9.898822e+10    6.661594e+09
1   AGROT.IS  3.260604e+08      16485488640  3.627482e+09    1.632251e+09
2   AKFGY.IS  1.380940e+09      10300974080  1.318659e+06    3.176869e+09
3   AKFYE.IS  4.425387e+09      31549067264  2.985196e+10   -1.437775e+09
4    AKSA.IS  2.881952e+09      36068925440  1.273125e+10    2.883095e+09
..       ...           ...              ...           ...             ...
81  VESTL.IS  9.768663e+09      72822325248  3.617088e+10   -3.003280e+10
82  YYLGD.IS  1.245862e+09      17738612736  3.950490e+09    3.738446e+09
83  YEOTK.IS  8.261853e+08      17655279616  1.126468e+09    9.561731e+08
84  ZOREN.IS  1.195323e+10      59861598208  4.103111e+10   -1.173196e+10
85  BINHO.IS  5.435281e+09      17735081984  2.208400e+06    8.952079e+08

[86 rows x 5 columns]

In [98]:
df["EarningsYield"] = df["ebit"] / df["enterpriseValue"]
df["ROIC"] = df["ebit"] / (df["netPPE"] + df["workingCapital"])
df

,stock,ebit,enterpriseValue,netPPE,workingCapital,EarningsYield,ROIC
0,AGHOL.IS,7.657792e+10,248437800960,9.898822e+10,6.661594e+09,0.308238,0.724828
1,AGROT.IS,3.260604e+08,16485488640,3.627482e+09,1.632251e+09,0.019779,0.061992
2,AKFGY.IS,1.380940e+09,10300974080,1.318659e+06,3.176869e+09,0.134059,0.434506
3,AKFYE.IS,4.425387e+09,31549067264,2.985196e+10,-1.437775e+09,0.140270,0.155746
4,AKSA.IS,2.881952e+09,36068925440,1.273125e+10,2.883095e+09,0.079901,0.184571
...,...,...,...,...,...,...,...
81,VESTL.IS,9.768663e+09,72822325248,3.617088e+10,-3.003280e+10,0.134144,1.591486
82,YYLGD.IS,1.245862e+09,17738612736,3.950490e+09,3.738446e+09,0.070234,0.162033
83,YEOTK.IS,8.261853e+08,17655279616,1.126468e+09,9.561731e+08,0.046795,0.396701
84,ZOREN.IS,1.195323e+10,59861598208,4.103111e+10,-1.173196e+10,0.199681,0.407972
85,BINHO.IS,5.435281e+09,17735081984,2.208400e+06,8.952079e+08,0.306471,6.056589

In [99]:
df["EarningsYieldRank"] = df["EarningsYield"].rank(ascending=False)
df["ROICRank"] = df["ROIC"].rank(ascending=False)
df

,stock,ebit,enterpriseValue,netPPE,workingCapital,EarningsYield,ROIC,EarningsYieldRank,ROICRank
0,AGHOL.IS,7.657792e+10,248437800960,9.898822e+10,6.661594e+09,0.308238,0.724828,2.0,16.0
1,AGROT.IS,3.260604e+08,16485488640,3.627482e+09,1.632251e+09,0.019779,0.061992,76.0,78.0
2,AKFGY.IS,1.380940e+09,10300974080,1.318659e+06,3.176869e+09,0.134059,0.434506,28.0,31.0
3,AKFYE.IS,4.425387e+09,31549067264,2.985196e+10,-1.437775e+09,0.140270,0.155746,24.0,66.0
4,AKSA.IS,2.881952e+09,36068925440,1.273125e+10,2.883095e+09,0.079901,0.184571,45.0,59.0
...,...,...,...,...,...,...,...,...,...
81,VESTL.IS,9.768663e+09,72822325248,3.617088e+10,-3.003280e+10,0.134144,1.591486,27.0,4.0
82,YYLGD.IS,1.245862e+09,17738612736,3.950490e+09,3.738446e+09,0.070234,0.162033,51.0,63.0
83,YEOTK.IS,8.261853e+08,17655279616,1.126468e+09,9.561731e+08,0.046795,0.396701,62.0,34.0
84,ZOREN.IS,1.195323e+10,59861598208,4.103111e+10,-1.173196e+10,0.199681,0.407972,12.0,32.0
85,BINHO.IS,5.435281e+09,17735081984,2.208400e+06,8.952079e+08,0.306471,6.056589,3.0,3.0

In [100]:
df["CombinedRank"] = df["EarningsYieldRank"] + df["ROICRank"]
df["MagicFormulaRank"] = df["CombinedRank"].rank()
df.sort_values("MagicFormulaRank", inplace=True)
df

,stock,ebit,enterpriseValue,netPPE,workingCapital,EarningsYield,ROIC,EarningsYieldRank,ROICRank,CombinedRank,MagicFormulaRank
85,BINHO.IS,5.435281e+09,17735081984,2.208400e+06,8.952079e+08,0.306471,6.056589,3.0,3.0,6.0,1.0
37,ISGYO.IS,4.579515e+09,21254623232,2.563238e+08,4.687947e+08,0.215460,6.315540,9.0,2.0,11.0,2.0
69,TKNSA.IS,2.453218e+09,6893279232,1.798751e+09,8.822790e+08,0.355885,0.915028,1.0,11.0,12.0,3.0
0,AGHOL.IS,7.657792e+10,248437800960,9.898822e+10,6.661594e+09,0.308238,0.724828,2.0,16.0,18.0,4.0
27,ENJSA.IS,1.585882e+10,98829606912,7.478974e+09,-7.317999e+09,0.160466,98.517292,19.0,1.0,20.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...
17,BFREN.IS,1.390358e+07,22945503232,2.819679e+08,8.463797e+07,0.000606,0.037925,83.0,79.0,162.0,82.0
47,KOZAL.IS,1.800630e+08,64464916480,4.872990e+09,9.611072e+09,0.002793,0.012432,82.0,83.0,165.0,83.0
48,KOZAA.IS,-1.441270e+08,25077166080,6.570958e+09,1.016670e+10,-0.005747,-0.008611,84.0,84.0,168.0,84.0
68,TKFEN.IS,-6.232140e+08,19448647680,1.589228e+10,2.954510e+08,-0.032044,-0.038499,85.0,85.0,170.0,85.0
26,EKGYO.IS,-2.811176e+09,44765978624,1.137555e+09,5.163250e+10,-0.062797,-0.053272,86.0,86.0,172.0,86.0

In [102]:
df.to_excel("magic_formula_result_bist100.xlsx")